# Generated by Django 4.1.3 on 2022-11-13 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('events', '0002_remove_eventpage_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Зображення'),
        ),
        migrations.AddField(
            model_name='eventspage',
            name='keywords',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Ключові слова для пошуку'),
        ),
    ]
