# Generated by Django 4.1.3 on 2022-11-13 08:35

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_homepage_options_homepage_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', wagtail.fields.RichTextField(verbose_name='Зміст')),
            ],
            options={
                'verbose_name': 'Футтер',
                'verbose_name_plural': 'Футтери',
            },
        ),
        migrations.AddField(
            model_name='homepage',
            name='keywords',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Ключові слова для пошуку'),
        ),
    ]
